### ISSUE TITLE
yaml - properies will overwrite

### ISSUE THREAD

**Issue by Skeeve** [rkrombho/getch#31]
When having 2 yaml files like

    a:
      b: value

and

    a:
      c: value

one will overwrite the other, so you will either be able to use a.b or a.c but not both of them.

**Comment by rkrombho** [comment]
This also works now (fixed in 96afa747799f5493afe9a4d715bbe1823f9a4127).

What does **not** work if you in this situation query for 'b' and expect to get a merged view of both files.
Implementing this would quite a significant rework.
